name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
  tag-release:
    runs-on: ubuntu-latest
    needs: test
    name: Tag Release
    # Only run this job if the repository is owned by 'pantheon-systems' and the branch is the default branch
    if: ${{ github.repository_owner == 'pantheon-systems' && github.ref_name == github.event.repository.default_branch }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pantheon-systems/action-autotag@v1
        with:
          v-prefix: false
          github_token: ${{ secrets.AUTOTAG_GH_TOKEN }}